### ISSUE TITLE
Add time stamp to the working directory or allow overwritting

### ISSUE THREAD

**Issue by SarahAlidoost** [SDCCA/DGL-PTM#44]
Currently, the model identifier is used to create the working directory. If users re-run an experiment with the same identifier, it might fail because the working directory exists. Solution either add a time stamp to the name of the working dir or allow overwritting.

**Comment by vanlankveldthijs** [comment]
We recently decided not to add the timestamp to the directory, because this would make it harder to find the specific runs you're looking for.
Also, when re-running an experiment, we expect that the experiment would have to load the starting model state for the re-run, which would require the model to be stored in the same directory.

Instead, when (re)starting a run, the config is stored to a new (unique) file. The timestamp of this file could be used in case you need to identify a run by its starting time.
