### ISSUE TITLE
Track number of connections in network

### ISSUE THREAD

**Issue by meiertgrootes** [SDCCA/DGL-PTM#69]
Depending on destruction and creation of links the number of links in the network evolves. We would like to track this parameter explicitly and make it accessible via the model class to enable control and possible feedback.

**Comment by SarahAlidoost** [comment]
For tracking there is a function` self.model_graph.number_of_edges()` that can be made explicit. The `model_graph` is created in `initialize_model()` and updated in `step()`. 

Regarding updating (giving feedback), currently, it is possible to pass `new_node_edges` through `network_creation`. However, this will re-create the graph instead of updating it. So, there should be an update function. We can use dgl functions like [add_edges](https://docs.dgl.ai/en/1.1.x/generated/dgl.DGLGraph.add_edges.html#dgl-dglgraph-add-edges) and [remove_edges](https://docs.dgl.ai/en/1.1.x/generated/dgl.DGLGraph.remove_edges.html#dgl-dglgraph-remove-edges).

**Comment by meiertgrootes** [comment]
Indeed adding and removing edges should be done using the add_edges remove_edges dgl functions. These also underly the edge creation/deletion functions we currently have, which we are modifying (where necessary) to accept a specified number off edges to create/delete. If we make the number explicit in the model class we can suffice with passing only the number to any other logic we want to implement, rather than the full graph object.
