### ISSUE TITLE
Possible Bug: Must be transferred to CPU before property collection

### ISSUE THREAD

**Issue by vmgaribay** [SDCCA/DGL-PTM#87]
Line 33 of data_collection.py

maybe lines 45 and 46 too

I had to do an emergency fix to allow it to run on snellius gpu, it may not be the best.

**Comment by SarahAlidoost** [comment]
I found your fix at line 33 in the `data_collection.py` [here](https://github.com/SDCCA/DGL-PTM/commit/81a6ceb6e24195916fdc121355d84ab5b10506bf#diff-0d73dc73586ecc7b8714eb32930f375a9e8a5d60bbd72bf48bb5163e36453409) plus the changes to the `initialize_model.py`  [here](https://github.com/SDCCA/DGL-PTM/commit/81a6ceb6e24195916fdc121355d84ab5b10506bf#diff-81b4520fb41b7755765a250239a8b928dd2cc3865e67478a946b8f2599d3d8ac). 
Despite your changes, the test [gpu_sample_run.py](https://github.com/SDCCA/DGL-PTM/blob/master/DGL_testing/gpu_sample_run.py) from `development` branch still fails, whereas it passes in the `master` branch. The reason is that in [agent_update.py](https://github.com/SDCCA/DGL-PTM/blob/81c6574be01e1b76d9f0cb952e5f580d6bb54c8f/dgl_ptm/dgl_ptm/agent/agent_update.py#L7) default value of `device` is `None`. In `step.py,` `agent_update` is called without setting the argument `device`, see [here](https://github.com/SDCCA/DGL-PTM/blob/81c6574be01e1b76d9f0cb952e5f580d6bb54c8f/dgl_ptm/dgl_ptm/model/step.py#L40) as an example. This issue is fixed in #103 and test `gpu_sample_run.py` now passes successfully. The irrelevant changes have also been corrected.

Additional info about your fix to `data_collection.py`: The `.to("cpu")` method in DGL is similar to the `.cpu()` method in PyTorch. Both methods are used to move data from GPU to CPU.

**Comment by SarahAlidoost** [comment]
fixed by #103
